--- === TextClipboardHistory ===
---
--- Keep a history of the clipboard, only for text entries
---
--- Originally based on [code by VFS](https://github.com/VFS/.hammerspoon/blob/master/tools/clipboard.lua), but with many changes and some contributions and inspiration from [asmagill](https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua).
---
--- Download: [https://github.com/Hammerspoon/Spoons/raw/master/Spoons/TextClipboardHistory.spoon.zip](https://github.com/Hammerspoon/Spoons/raw/master/Spoons/TextClipboardHistory.spoon.zip)

local obj={}
obj.__index = obj

-- Metadata
obj.name = "TextClipboardHistory"
obj.version = "0.5"
obj.author = "Diego Zamboni <diego@zzamboni.org>"
obj.homepage = "https://github.com/Hammerspoon/Spoons"
obj.license = "MIT - https://opensource.org/licenses/MIT"

local getSetting = function(label, default) return hs.settings.get(obj.name.."."..label) or default end
local setSetting = function(label, value)   hs.settings.set(obj.name.."."..label, value); return value end

--- TextClipboardHistory.frequency
--- Variable
--- Speed in seconds to check for clipboard changes. If you check too frequently, you will degrade performance, if you check sparsely you will loose copies. Defaults to 0.8.
obj.frequency = 0.8

--- TextClipboardHistory.hist_size
--- Variable
--- How many items to keep on history. Defaults to 100
obj.hist_size = 100

--- TextClipboardHistory.honor_ignoredidentifiers
--- Variable
--- If `true`, check the data identifiers set in the pasteboard and ignore entries which match those listed in `TextClipboardHistory.ignoredIdentifiers`. The list of identifiers comes from http://nspasteboard.org. Defaults to `true`
obj.honor_ignoredidentifiers = true

--- TextClipboardHistory.paste_on_select
--- Variable
--- Whether to auto-type the item when selecting it from the menu. Can be toggled on the fly from the chooser. Defaults to `false`.
obj.paste_on_select = getSetting('paste_on_select', false)

--- TextClipboardHistory.logger
--- Variable
--- Logger object used within the Spoon. Can be accessed to set the default log level for the messages coming from the Spoon.
obj.logger = hs.logger.new('TextClipboardHistory')

--- TextClipboardHistory.ignoredIdentifiers
--- Variable
--- Types of clipboard entries to ignore, see http://nspasteboard.org. Code from https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua. Default value (don't modify unless you know what you are doing):
--- ```
---  {
---     ["de.petermaurer.TransientPasteboardType"] = true, -- Transient : Textpander, TextExpander, Butler
---     ["com.typeit4me.clipping"]                 = true, -- Transient : TypeIt4Me
---     ["Pasteboard generator type"]              = true, -- Transient : Typinator
---     ["com.agilebits.onepassword"]              = true, -- Confidential : 1Password
---     ["org.nspasteboard.TransientType"]         = true, -- Universal, Transient
---     ["org.nspasteboard.ConcealedType"]         = true, -- Universal, Concealed
---     ["org.nspasteboard.AutoGeneratedType"]     = true, -- Universal, Automatic
---  }
--- ```
obj.ignoredIdentifiers = {
   ["de.petermaurer.TransientPasteboardType"] = true, -- Transient : Textpander, TextExpander, Butler
   ["com.typeit4me.clipping"]                 = true, -- Transient : TypeIt4Me
   ["Pasteboard generator type"]              = true, -- Transient : Typinator
   ["com.agilebits.onepassword"]              = true, -- Confidential : 1Password
   ["org.nspasteboard.TransientType"]         = true, -- Universal, Transient
   ["org.nspasteboard.ConcealedType"]         = true, -- Universal, Concealed
   ["org.nspasteboard.AutoGeneratedType"]     = true, -- Universal, Automatic
}

--- TextClipboardHistory.deduplicate
--- Variable
--- Whether to remove duplicates from the list, keeping only the latest one. Defaults to `true`.
obj.deduplicate = true

--- TextClipboardHistory.show_in_menubar
--- Variable
--- Whether to show a menubar item to open the clipboard history. Defaults to `true`
obj.show_in_menubar = true

--- TextClipboardHistory.menubar_title
--- Variable
--- String to show in the menubar if `TextClipboardHistory.show_in_menubar` is `true`. Defaults to `"\u{1f4ce}"`, which is the [Unicode paperclip character](https://codepoints.net/U+1F4CE)
obj.menubar_title   = "\u{1f4ce}"

--- TextClipboardHistory.highlight_search_matches
--- Variable
--- Whether to highlight search matches in the chooser. Defaults to `true`.
obj.highlight_search_matches = true

--- TextClipboardHistory.enableSnippets
--- Variable
--- Whether to enable snippets from config file. Defaults to `true`
obj.enableSnippets = true

--- TextClipboardHistory.snippetFilePath
--- Variable
--- Path to the snippets config file. Defaults to `~/.config/hammerspoon/snippets.txt`
obj.snippetFilePath = os.getenv("HOME") .. "/.config/hammerspoon/snippets.txt"

----------------------------------------------------------------------

-- Internal variable - Snippets list
obj.snippets = nil
-- Internal variable - Snippet access history (for LRU sorting)
obj.snippetHistory = nil
-- Internal variable - Clipboard history access timestamps (for LRU sorting)
obj.clipboardHistoryLRU = nil
obj.selectorobj = nil
-- Internal variable - Cache for focused window to work around the current window losing focus after the chooser comes up
obj.prevFocusedWindow = nil
-- Internal variable - Timer object to look for pasteboard changes
obj.timer = nil
-- Internal variable - Cache for menu data to improve search performance
obj.menuDataCache = nil
-- Internal variable - Cache for filtered menu data
obj.filteredMenuDataCache = nil
-- Internal variable - Last search query to avoid unnecessary recalculation
obj.lastSearchQuery = ""

local pasteboard = require("hs.pasteboard") -- http://www.hammerspoon.org/docs/hs.pasteboard.html
local hashfn   = require("hs.hash").MD5

-- Keep track of last change counter
local last_change = nil;
-- Array to store the clipboard history
local clipboard_history = nil

-- Internal function - persist the current history so it survives across restarts
function _persistHistory()
   setSetting("items",clipboard_history)
end

--- TextClipboardHistory:togglePasteOnSelect()
--- Method
--- Toggle the value of `TextClipboardHistory.paste_on_select`
function obj:togglePasteOnSelect()
   self.paste_on_select = setSetting("paste_on_select", not self.paste_on_select)
   hs.notify.show("TextClipboardHistory", "Paste-on-select is now " .. (self.paste_on_select and "enabled" or "disabled"), "")
end

-- Internal variable - File watcher for snippets
obj.snippetFileWatcher = nil

-- Internal method - Load snippets from config file
-- Format: snippets separated by empty lines, each snippet can have multiple lines
function obj:loadSnippets()
   if not self.enableSnippets then
      self.snippets = {}
      return
   end

   local file = io.open(self.snippetFilePath, "r")
   if not file then
      self.snippets = {}
      return
   end

   local content = file:read("*a")
   file:close()

   if not content or content == "" then
      self.snippets = {}
      return
   end

   -- Parse snippets: split by empty lines, using Set to avoid duplicates
   local snippets = {}
   local seen = {}
   for snippet in content:gmatch("(.-)\n\n+") do
      -- Remove trailing whitespace/newlines from each snippet
      snippet = snippet:gsub("%s+$", "")
      if snippet and snippet ~= "" and not seen[snippet] then
         seen[snippet] = true
         table.insert(snippets, snippet)
      end
   end

   -- Handle case where there's no trailing empty line
   local lastSnippet = content:match(".-%S.*$")
   if lastSnippet and lastSnippet:match("%S") then
      lastSnippet = lastSnippet:gsub("%s+$", "")
      if lastSnippet and lastSnippet ~= "" and not seen[lastSnippet] then
         seen[lastSnippet] = true
         table.insert(snippets, lastSnippet)
      end
   end

   self.snippets = snippets
   self.logger.df("Loaded %d snippets from %s", #snippets, self.snippetFilePath)

   -- Clear cache when snippets are reloaded
   self.menuDataCache = nil
   self.filteredMenuDataCache = nil
   self.lastSearchQuery = ""
end

-- Internal method - Use a snippet (copy to clipboard and update LRU)
function obj:useSnippet(snippetContent)
   if not snippetContent then
      return
   end

   -- Update LRU history
   self.snippetHistory[snippetContent] = os.time()
   setSetting("snippetHistory", self.snippetHistory)

   -- Copy to clipboard
   pasteboard.setContents(snippetContent)
   self:pasteboardToClipboard(snippetContent)

   -- Auto-paste
   hs.eventtap.keyStroke({"cmd"}, "v")

   last_change = pasteboard.changeCount()
end

-- Internal method - process the selected item from the chooser. An item may invoke special actions, defined in the `actions` variable.
function obj:_processSelectedItem(value)
   local actions = {
      none = function() end,
      clear = hs.fnutils.partial(self.clearAll, self),
      toggle_paste_on_select = hs.fnutils.partial(self.togglePasteOnSelect, self),
   }
   if self.prevFocusedWindow ~= nil then
      self.prevFocusedWindow:focus()
   end
   if value and type(value) == "table" then
      if value.action and actions[value.action] then
         actions[value.action](value)
      elseif value.isSnippet and value.originalText then
         -- Handle snippet selection
         self:useSnippet(value.originalText)
      elseif value.text and not value.action then
         -- Use originalText if available (for truncated entries), otherwise use text
         local textToUse = value.originalText or value.text

         -- Update LRU for clipboard history item
         self.clipboardHistoryLRU[textToUse] = os.time()
         setSetting("clipboardHistoryLRU", self.clipboardHistoryLRU)

         pasteboard.setContents(textToUse)
         self:pasteboardToClipboard(textToUse)
         if (self.paste_on_select) then
            hs.eventtap.keyStroke({"cmd"}, "v")
         end
      end
      last_change = pasteboard.changeCount()
   end
end

--- TextClipboardHistory:clearAll()
--- Method
--- Clears the clipboard and history
function obj:clearAll()
   pasteboard.clearContents()
   clipboard_history = {}
   _persistHistory()
   last_change = pasteboard.changeCount()

   -- Clear LRU history
   self.clipboardHistoryLRU = {}
   setSetting("clipboardHistoryLRU", {})

   -- Clear cache when history is cleared
   self.menuDataCache = nil
   self.filteredMenuDataCache = nil
   self.lastSearchQuery = ""
end

--- TextClipboardHistory:clearLastItem()
--- Method
--- Clears the last added to the history
function obj:clearLastItem()
   table.remove(clipboard_history, 1)
   _persistHistory()
   last_change = pasteboard.changeCount()
   
   -- Clear cache when history changes
   self.menuDataCache = nil
   self.filteredMenuDataCache = nil
   self.lastSearchQuery = ""
end

-- Internal method: Highlight matching text in search results
function obj:_highlightMatches(text, query)
   if not query or query == "" then
      return text
   end
   
   local queryLower = string.lower(query)
   local textLower = string.lower(text)
   
   -- Find the first occurrence of the query
   local startPos, endPos = string.find(textLower, queryLower, 1, true)
   if startPos then
      -- Add visual indicators around the match
      local before = string.sub(text, 1, startPos - 1)
      local match = string.sub(text, startPos, endPos)
      local after = string.sub(text, endPos + 1)
      return before .. "【" .. match .. "】" .. after
   end
   
   return text
end

-- Internal method: Smart search filtering with fuzzy matching
function obj:_filterMenuData(menuData, query)
   if not query or query == "" then
      return menuData
   end
   
   local filtered = {}
   local queryLower = string.lower(query)
   
   -- Split query into words for multi-word search
   local queryWords = {}
   for word in string.gmatch(queryLower, "%S+") do
      table.insert(queryWords, word)
   end
   
   for _, item in ipairs(menuData) do
      if item.action then
         -- Always include control items (clear, toggle, etc.)
         table.insert(filtered, item)
      elseif item.text and item.originalText then
         local textLower = string.lower(item.originalText)
         local displayTextLower = string.lower(item.text)
         
         -- Check if all query words are found in the text
         local allWordsFound = true
         for _, word in ipairs(queryWords) do
            if not string.find(textLower, word, 1, true) and 
               not string.find(displayTextLower, word, 1, true) then
               allWordsFound = false
               break
            end
         end
         
         if allWordsFound then
            -- Calculate relevance score for sorting
            local score = 0
            
            -- Exact match gets highest score
            if textLower == queryLower then
               score = 1000
            -- Starts with query gets high score
            elseif string.find(textLower, "^" .. queryLower) then
               score = 500
            -- Contains query as whole word gets medium score
            elseif string.find(textLower, "%f[%w]" .. queryLower .. "%f[%W]") then
               score = 100
            -- Contains query gets base score
            else
               score = 10
            end
            
            -- Boost score for shorter text (more relevant)
            score = score + (1000 / math.max(string.len(item.originalText), 1))
            
            -- Create a copy of the item with highlighted text
            local highlightedItem = {}
            for k, v in pairs(item) do
               highlightedItem[k] = v
            end
            
            -- Highlight matches in the display text if enabled
            if self.highlight_search_matches then
               highlightedItem.text = self:_highlightMatches(item.text, query)
            end
            highlightedItem.searchScore = score
            
            table.insert(filtered, highlightedItem)
         end
      end
   end
   
   -- Sort by relevance score (higher is better)
   table.sort(filtered, function(a, b)
      local scoreA = a.searchScore or 0
      local scoreB = b.searchScore or 0
      return scoreA > scoreB
   end)
   
   return filtered
end

-- Internal method: deduplicate the given list, and restrict it to the history size limit
function obj:dedupe_and_resize(list)
   local res={}
   local hashes={}
   for i,v in ipairs(list) do
      if #res < self.hist_size then
         local hash=hashfn(v)
         if (not self.deduplicate) or (not hashes[hash]) then
            table.insert(res, v)
            hashes[hash]=true
         end
      end
   end
   return res
end

--- TextClipboardHistory:pasteboardToClipboard(item)
--- Method
--- Add the given string to the history
---
--- Parameters:
---  * item - string to add to the clipboard history
---
--- Returns:
---  * None
function obj:pasteboardToClipboard(item)
   table.insert(clipboard_history, 1, item)
   clipboard_history = self:dedupe_and_resize(clipboard_history)
   _persistHistory() -- updates the saved history
   
   -- Clear cache when history changes
   self.menuDataCache = nil
   self.filteredMenuDataCache = nil
   self.lastSearchQuery = ""
end

-- Internal function - fill in the chooser options, including the control options
function obj:_populateChooser()
   -- Use cached data if available and clipboard hasn't changed
   if self.menuDataCache and last_change == pasteboard.changeCount() then
      return self.menuDataCache
   end

   local menuData = {}

   -- Build items for sorting
   local allItems = {}

   -- Add snippets with LRU timestamp
   if self.enableSnippets and self.snippets and #self.snippets > 0 then
      for _, snippet in ipairs(self.snippets) do
         local displayText = snippet
         local maxLength = 200
         if string.len(snippet) > maxLength then
            displayText = string.sub(snippet, 1, maxLength) .. "..."
         end
         displayText = string.gsub(displayText, "\n", " ")
         displayText = string.gsub(displayText, "\r", " ")

         table.insert(allItems, {
            text = "📋 " .. displayText,
            subText = "Snippet",
            originalText = snippet,
            isSnippet = true,
            lruTime = self.snippetHistory[snippet] or 0
         })
      end
   end

   -- Add clipboard history (index 1 = most recent)
   for idx, v in ipairs(clipboard_history) do
      if (type(v) == "string") then
         local displayText = v
         local maxLength = 200
         if string.len(v) > maxLength then
            displayText = string.sub(v, 1, maxLength) .. "..."
         end
         displayText = string.gsub(displayText, "\n", " ")
         displayText = string.gsub(displayText, "\r", " ")

         -- Use LRU timestamp if available, otherwise use index as fallback
         local lruTime = self.clipboardHistoryLRU[v]
         if not lruTime then
            -- Give newer items higher timestamps based on index
            lruTime = 1000000000 + (1000 - idx)
         end

         table.insert(allItems, {
            text = displayText,
            subText = "",
            originalText = v,
            isSnippet = false,
            lruTime = lruTime
         })
      end
   end

   -- Sort by LRU (higher lruTime = more recent first)
   table.sort(allItems, function(a, b)
      return (a.lruTime or 0) > (b.lruTime or 0)
   end)

   -- Copy sorted items to menuData
   for _, item in ipairs(allItems) do
      table.insert(menuData, item)
   end

   -- Add control items
   if #menuData == 0 then
      table.insert(menuData, { text="",
                               subText="《Clipboard is empty》",
                               action = 'none',
                               image = hs.image.imageFromName('NSCaution')})
   else
      table.insert(menuData, { text="《Clear Clipboard History》",
                               action = 'clear',
                               image = hs.image.imageFromName('NSTrashFull') })
   end
   table.insert(menuData, {
                   text="《" .. (self.paste_on_select and "Disable" or "Enable") .. " Paste-on-select》",
                   action = 'toggle_paste_on_select',
                   image = (self.paste_on_select and hs.image.imageFromName('NSSwitchEnabledOn') or hs.image.imageFromName('NSSwitchEnabledOff'))
   })

   -- Cache the menu data
   self.menuDataCache = menuData
   self.logger.df("Populated %d clipboard items", #menuData - 2)
   return menuData
end

-- Internal function - populate chooser with search filtering
function obj:_populateChooserWithSearch(query)
   local baseMenuData = self:_populateChooser()
   
   -- If no query, return all items
   if not query or query == "" then
      self.lastSearchQuery = ""
      return baseMenuData
   end
   
   -- If query hasn't changed, return cached results
   if query == self.lastSearchQuery and self.filteredMenuDataCache then
      return self.filteredMenuDataCache
   end
   
   -- Filter and cache results
   local filteredData = self:_filterMenuData(baseMenuData, query)
   self.filteredMenuDataCache = filteredData
   self.lastSearchQuery = query
   
   self.logger.df("Filtered to %d items for query: %s", #filteredData, query)
   return filteredData
end

--- TextClipboardHistory:shouldBeStored()
--- Method
--- Verify whether the pasteboard contents matches one of the values in `TextClipboardHistory.ignoredIdentifiers`
function obj:shouldBeStored()
   -- Code from https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua
   local goAhead = true
   for i,v in ipairs(hs.pasteboard.pasteboardTypes()) do
      if self.ignoredIdentifiers[v] then
         goAhead = false
         break
      end
   end
   if goAhead then
      for i,v in ipairs(hs.pasteboard.contentTypes()) do
         if self.ignoredIdentifiers[v] then
            goAhead = false
            break
         end
      end
   end
   return goAhead
end

--- TextClipboardHistory:checkAndStorePasteboard()
--- Method
--- If the pasteboard has changed, we add the current item to our history and update the counter
function obj:checkAndStorePasteboard()
   now = pasteboard.changeCount()
   if (now > last_change) then
      if (not self.honor_ignoredidentifiers) or self:shouldBeStored() then
         current_clipboard = pasteboard.getContents()
         self.logger.df("current_clipboard = %s", tostring(current_clipboard))
         if (current_clipboard == nil) and (pasteboard.readImage() ~= nil) then
            self.logger.df("Images not yet supported - ignoring image contents in clipboard")
         elseif current_clipboard ~= nil then
            self.logger.df("Adding %s to clipboard history", current_clipboard)
            self:pasteboardToClipboard(current_clipboard)
         else
            self.logger.df("Ignoring nil clipboard content")
         end
      else
         self.logger.df("Ignoring pasteboard entry because it matches ignoredIdentifiers")
      end
      last_change = now
   end
end

--- TextClipboardHistory:start()
--- Method
--- Start the clipboard history collector
function obj:start()
   -- Load snippets from config file
   self:loadSnippets()

   -- Set up file watcher for snippets
   if self.snippetFileWatcher then
      self.snippetFileWatcher:stop()
   end
   self.snippetFileWatcher = hs.pathwatcher.new(self.snippetFilePath, function(path)
      self.logger.df("Snippets file changed, reloading...")
      self:loadSnippets()
   end)
   self.snippetFileWatcher:start()

   -- Initialize snippet history (for LRU)
   self.snippetHistory = getSetting("snippetHistory", {})

   -- Initialize clipboard history LRU timestamps
   self.clipboardHistoryLRU = getSetting("clipboardHistoryLRU", {})

   clipboard_history = self:dedupe_and_resize(getSetting("items", {})) -- If no history is saved on the system, create an empty history
   last_change = pasteboard.changeCount() -- keeps track of how many times the pasteboard owner has changed // Indicates a new copy has been made
   self.selectorobj = hs.chooser.new(hs.fnutils.partial(self._processSelectedItem, self))
   
   -- Set up dynamic search filtering
   self.selectorobj:queryChangedCallback(function(query)
      local filteredChoices = self:_populateChooserWithSearch(query)
      self.selectorobj:choices(filteredChoices)
   end)
   
   -- Initial population
   self.selectorobj:choices(hs.fnutils.partial(self._populateChooser, self))

   --Checks for changes on the pasteboard. Is it possible to replace with eventtap?
   self.timer = hs.timer.new(self.frequency, hs.fnutils.partial(self.checkAndStorePasteboard, self))
   self.timer:start()
   if self.show_in_menubar then
      self.menubaritem = hs.menubar.new()
         :setTitle(obj.menubar_title)
         :setClickCallback(hs.fnutils.partial(self.toggleClipboard, self))
   end
end

--- TextClipboardHistory:showClipboard()
--- Method
--- Display the current clipboard list in a chooser
function obj:showClipboard()
   if self.selectorobj ~= nil then
      self.selectorobj:refreshChoicesCallback()
      self.prevFocusedWindow = hs.window.focusedWindow()
      self.selectorobj:show()
   else
      hs.notify.show("TextClipboardHistory not properly initialized", "Did you call TextClipboardHistory:start()?", "")
   end
end

--- TextClipboardHistory:toggleClipboard()
--- Method
--- Show/hide the clipboard list, depending on its current state
function obj:toggleClipboard()
   if self.selectorobj:isVisible() then
      self.selectorobj:hide()
   else
      self:showClipboard()
   end
end

--- TextClipboardHistory:stop()
--- Method
--- Stop the clipboard history collector and clean up resources
function obj:stop()
   if self.snippetFileWatcher then
      self.snippetFileWatcher:stop()
      self.snippetFileWatcher = nil
   end
   if self.timer then
      self.timer:stop()
      self.timer = nil
   end
   if self.menubaritem then
      self.menubaritem:delete()
      self.menubaritem = nil
   end
end

--- TextClipboardHistory:bindHotkeys(mapping)
--- Method
--- Binds hotkeys for TextClipboardHistory
---
--- Parameters:
---  * mapping - A table containing hotkey objifier/key details for the following items:
---   * show_clipboard - Display the clipboard history chooser
---   * toggle_clipboard - Show/hide the clipboard history chooser
function obj:bindHotkeys(mapping)
   local def = {
      show_clipboard = hs.fnutils.partial(self.showClipboard, self),
      toggle_clipboard = hs.fnutils.partial(self.toggleClipboard, self),
   }
   hs.spoons.bindHotkeysToSpec(def, mapping)
end

return obj

